"""Audit NGSIM US-101 / I-80 freeway platoons (scheme C §6.2 Step 1).

Discovers the six freeway period CSVs, extracts compositionally-stable
N-vehicle platoons with the *same* protocol as the HighD main experiment
(no lane change, positive gaps, consistent ordering), and reports how many
survive the non-stationary leader filter at each quantile together with the
number of history+predict sliding windows they yield. The per-site window
counts feed the §6.2 zero-shot Go/No-Go decision.

The window count uses the exact resampling/slicing arithmetic of
``data.windowing`` so it matches what ``build_ngsim_platoon_samples`` will
actually emit (NGSIM is natively 10 Hz, so resampling is the identity).
"""

from __future__ import annotations

import argparse
import logging
from dataclasses import asdict, dataclass
from math import floor
from pathlib import Path

import numpy as np
import pandas as pd

from ..data.ngsim import discover_ngsim_recordings
from ..data.platoons import (
    PlatoonExtractionConfig,
    PlatoonSegment,
    PlatoonStationarityThresholds,
    extract_platoon_segments,
    filter_segments_by_stationarity,
)
from ..data.windowing import WindowingConfig

_log = logging.getLogger("ssp.audit_ngsim")


def _resampled_length(num_frames: int, source_hz: float, target_hz: float) -> int:
    if abs(source_hz - target_hz) < 1e-6:
        return num_frames
    duration = (num_frames - 1) / source_hz
    return floor(duration * target_hz) + 1


def _count_windows(segment: PlatoonSegment, source_hz: float, win: WindowingConfig) -> int:
    length = _resampled_length(segment.num_frames, source_hz, win.target_hz)
    if length < win.total_steps:
        return 0
    if length / win.target_hz < win.minimum_total_seconds:
        return 0
    return (length - win.total_steps) // win.stride_steps + 1


@dataclass(slots=True)
class NGSIMAuditRow:
    site: str
    period: str
    recording_id: int
    N: int
    quantile: float
    num_segments: int
    total_segment_seconds: float
    median_segment_seconds: float
    num_windows: int


def audit_ngsim(
    recordings,
    extraction: PlatoonExtractionConfig,
    windowing: WindowingConfig,
    quantiles: tuple[float, ...],
) -> pd.DataFrame:
    rows: list[NGSIMAuditRow] = []
    for idx, rec in enumerate(recordings, start=1):
        _log.info(
            "Audit %d/%d: %s/%s (id=%d) extracting platoons N=%d..%d",
            idx,
            len(recordings),
            rec.site,
            rec.period,
            rec.recording_id,
            extraction.min_N,
            extraction.max_N,
        )
        all_segments = extract_platoon_segments(rec, extraction)
        per_n: dict[int, list[PlatoonSegment]] = {}
        for seg in all_segments:
            per_n.setdefault(seg.N, []).append(seg)
        _log.info(
            "  %s/%s raw segments=%d (per N: %s)",
            rec.site,
            rec.period,
            len(all_segments),
            {n: len(v) for n, v in sorted(per_n.items())},
        )
        for N in range(extraction.min_N, extraction.max_N + 1):
            segs_N = per_n.get(N, [])
            for q in quantiles:
                if q >= 1.0:
                    kept = segs_N
                else:
                    thresholds = PlatoonStationarityThresholds(
                        std_v_quantile=q, std_a_quantile=q, velocity_drop_quantile=q
                    )
                    kept = filter_segments_by_stationarity(rec, segs_N, thresholds)
                durations = np.asarray([s.duration_sec for s in kept], dtype=np.float64)
                num_windows = int(
                    sum(_count_windows(s, rec.frame_rate, windowing) for s in kept)
                )
                rows.append(
                    NGSIMAuditRow(
                        site=rec.site,
                        period=rec.period,
                        recording_id=rec.recording_id,
                        N=N,
                        quantile=float(q),
                        num_segments=len(kept),
                        total_segment_seconds=float(durations.sum()) if durations.size else 0.0,
                        median_segment_seconds=float(np.median(durations)) if durations.size else 0.0,
                        num_windows=num_windows,
                    )
                )
    df = pd.DataFrame([asdict(r) for r in rows])
    return df.sort_values(["site", "period", "N", "quantile"]).reset_index(drop=True)


def write_ngsim_audit_report(df: pd.DataFrame, out_dir: str | Path) -> tuple[Path, Path]:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    csv_path = out / "ngsim_platoon_audit.csv"
    df.to_csv(csv_path, index=False)

    lines = [
        "# NGSIM Freeway Platoon Audit (scheme C §6.2 Step 1)",
        "",
        "Auto-generated by `scripts/audit_ngsim_platoons.py`. `num_windows` counts",
        "history+predict sliding windows per the windowing config (NGSIM native 10 Hz).",
        "",
    ]

    per_site = (
        df.groupby(["site", "N", "quantile"], sort=True)
        .agg(
            periods=("period", "nunique"),
            num_segments=("num_segments", "sum"),
            num_windows=("num_windows", "sum"),
            total_segment_seconds=("total_segment_seconds", "sum"),
        )
        .reset_index()
    )
    lines += [
        "## Per-site summary",
        "",
        "| site | N | quantile | periods | segments | windows | total_seconds |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for _, r in per_site.iterrows():
        lines.append(
            f"| {r['site']} | {int(r['N'])} | {r['quantile']:.2f} | {int(r['periods'])} | "
            f"{int(r['num_segments'])} | {int(r['num_windows'])} | {r['total_segment_seconds']:.1f} |"
        )

    lines += ["", "## Per-period detail", "", "| site | period | N | quantile | segments | windows | median_seg_s |", "| --- | --- | --- | --- | --- | --- | --- |"]
    for _, r in df.iterrows():
        lines.append(
            f"| {r['site']} | {r['period']} | {int(r['N'])} | {r['quantile']:.2f} | "
            f"{int(r['num_segments'])} | {int(r['num_windows'])} | {r['median_segment_seconds']:.2f} |"
        )

    md_path = out / "ngsim_platoon_audit.md"
    md_path.write_text("\n".join(lines), encoding="utf-8")
    return csv_path, md_path


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="NGSIM freeway platoon audit (scheme C §6.2).")
    parser.add_argument("--ngsim-root", type=Path, required=True, help="vehicle-trajectory-data directory")
    parser.add_argument("--report-dir", type=Path, required=True)
    parser.add_argument("--min-N", type=int, default=5)
    parser.add_argument("--max-N", type=int, default=5)
    parser.add_argument("--minimum-total-seconds", type=float, default=10.0)
    parser.add_argument("--history-sec", type=float, default=5.0)
    parser.add_argument("--predict-sec", type=float, default=3.0)
    parser.add_argument("--stride-sec", type=float, default=1.0)
    parser.add_argument("--target-hz", type=float, default=10.0)
    parser.add_argument("--quantiles", type=float, nargs="+", default=[1.0, 0.5])
    parser.add_argument("--log-level", type=str, default="INFO")
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    logging.basicConfig(level=args.log_level.upper(), format="[%(asctime)s][%(levelname)s] %(message)s")

    extraction = PlatoonExtractionConfig(
        min_N=args.min_N,
        max_N=args.max_N,
        min_segment_seconds=args.minimum_total_seconds,
        require_no_lane_change=True,
        require_positive_gap=True,
    )
    windowing = WindowingConfig(
        target_hz=args.target_hz,
        history_seconds=args.history_sec,
        predict_seconds=args.predict_sec,
        stride_seconds=args.stride_sec,
        minimum_total_seconds=args.minimum_total_seconds,
    )
    _log.info("Discovering NGSIM recordings under %s", args.ngsim_root)
    recordings = discover_ngsim_recordings(args.ngsim_root)
    _log.info("Found %d NGSIM freeway recordings", len(recordings))
    df = audit_ngsim(recordings, extraction, windowing, tuple(args.quantiles))
    csv_path, md_path = write_ngsim_audit_report(df, args.report_dir)
    _log.info("Wrote audit CSV: %s", csv_path)
    _log.info("Wrote audit Markdown: %s", md_path)

    n5 = df[df["N"] == args.min_N]
    for _, r in n5.iterrows():
        _log.info(
            "  %s/%s N=%d q=%.2f -> segments=%d windows=%d",
            r["site"], r["period"], int(r["N"]), r["quantile"], int(r["num_segments"]), int(r["num_windows"]),
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
